# Generated by Django 5.0.6 on 2024-05-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_at', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('descirtion', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
